### ISSUE TITLE
Libs directory missing

### ISSUE THREAD

**Issue by davidyoung8906** [uds-se/backstage#1]
I got following error message when trying to build the project:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file (jws) on project Backstage: The specified file '/home/Git/backstage/libs/edu.sussex.nlp.jws.beta.11.jar' not exists -> [Help 1]
```

It seems that the whole libs directory is missing.

**Comment by vitaliiavdiienko** [comment]
Fixed in 2d54506ea1b24d661dd306eb6683e048e12eaac5. Thanks for reporting.

Best Regards,
Vitalii
